[EIP1-7618] update application rejection reasons
cabinetoffice/eip-ero-notifications-api pull request #167
Opened 2023-10-23 15:42 UTC by sgrubb

Update application rejection reasons user friendly text and add new rejection reasons

2023-10-23 15:58 UTC, sgrubb commented on src/main/resources/openapi/NotificationsAPIs.yaml
>          - fraudulent-application
Do I need to update the version at the top of these files?

2023-10-23 16:31 UTC, StephenPenney requested changes

2023-10-23 16:50 UTC, ralfleggettsoftwire commented on src/main/resources/messages.properties
>  templates.application-rejection.rejection-reasons.photo-is-not-acceptable= Your photo did not meet the criteria
sorry that's my fault. I was working on the VAC application approval / rejection messages focus issues (which _are_ sent through the notifications API) and forgot that postal and proxy do those messages through the EMSes.

I think the places that need changing in the postal/proxy API repos will be similar to what was touched in this PR, but sorry to have lead you down the wrong path @sgrubb

2023-11-14 14:03 UTC, StephenPenney commented
Closing as agreed not necessary

2023-11-14 14:03 UTC, closed without merging